- hosts: localhost
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /home/gpn/golang_app/
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy context with Dockerfile
      copy:
        src: /home/docker/golang_app/
        dest: /home/gpn/golang_app/
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: asemn00/golang_app_intern:latest
        source: build
        build:
          path: /home/gpn/golang_app
        state: present
    - name: run container
      docker_container:
          name: golang_app
          state: started
          image: "asemn00/golang_app_intern:latest"
          ports:
            - "3000:3000"
